name: Publish Notes to GitHub Pages

on:
  workflow_dispatch: # Enables on-demand/manual triggering
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Restore Node modules cache
      uses: actions/cache@v2
      id: node-modules-cache
      with:
        path: |
          node_modules
          .next/*
          !.next/.next/cache
          !.next/.env.*
        key: ${{ runner.os }}-dendronv2-${{ hashFiles('**/yarn.lock', '**/package-lock.json') }}

    - name: Install dependencies
      run: npx install-peerdeps --dev @dendronhq/cli

    - name: Initialize or pull nextjs template
      run: |
        if [ ! -d ".next" ]; then
          echo "Initializing dendron next..."
          npx dendron publish init
        else
          echo "Updating dendron next..."
          cd .next
          git reset --hard
          git pull
          npm install
          cd ..
        fi

    - name: Restore Next cache
      uses: actions/cache@v2
      with:
        path: |
          .next/.next/cache
          .next/server/bundle
          .next/static/chunks
        key: ${{ runner.os }}-nextjs-${{ hashFiles('.next/yarn.lock', '.next/package-lock.json') }}-${{ hashFiles('.next/**.[jt]s', '.next/**.[jt]sx') }}

    - name: Check dendron version
      run: npx dendron --version

    - name: Export notes
      run: npx dendron publish export --target github --yes

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: pages
        publish_dir: docs/
        force_orphan: true
