name: Build Dendron Static Site

on:
  workflow_dispatch: # Enables manual triggering
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout source code
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Step 2: Cache Node modules
      - name: Restore Node modules cache
        uses: actions/cache@v2
        id: node-modules-cache
        with:
          path: |
            node_modules
            .next/*
            !.next/.next/cache
            !.next/.env.*
          key: ${{ runner.os }}-dendronv2-${{ hashFiles('**/yarn.lock', '**/package-lock.json') }}

      # Step 3: Clear existing Node modules (optional but ensures clean state)
      - name: Clear Node modules
        run: rm -rf node_modules

      # Step 4: Install dependencies
      - name: Install dependencies
        run: yarn install

      # Step 5: Update critical dependencies to latest versions
      - name: Update React, Ant Design, and TypeScript
        run: |
          yarn add react@latest react-dom@latest antd@latest
          yarn add --dev typescript@latest @types/react @types/react-dom @types/antd

      # Step 6: Install types for lodash
      - name: Install @types/lodash
        run: yarn add --dev @types/lodash

      # Step 7: Remove private and template vaults
      - name: Remove private and template vaults
        run: |
          echo "Removing private and template vaults from dendron.yml..."
          sed -i '/- fsPath: templates/,+3d' dendron.yml
          sed -i '/- fsPath: vault2/,+6d' dendron.yml
          echo "Updated dendron.yml:"
          cat dendron.yml

      # Step 8: Initialize or pull Next.js template
      - name: Initialize or pull nextjs template
        run: |
          (test -d .next) && \
          (echo 'Updating Dendron Next.js template...' && cd .next && git reset --hard && git pull && yarn && cd ..) || \
          (echo 'Initializing Dendron Next.js template...' && yarn dendron publish init)

      # Step 9: Cache Next.js build
      - name: Restore Next.js cache
        uses: actions/cache@v2
        with:
          path: |
            .next/.next/cache
            .next/server/bundle
            .next/static/chunks
          key: ${{ runner.os }}-nextjs-${{ hashFiles('.next/yarn.lock', '.next/package-lock.json') }}-${{ hashFiles('.next/**.[jt]s', '.next/**.[jt]sx') }}

      # Step 10: Check Dendron version
      - name: Check dendron version
        run: yarn dendron --version

      # Step 11: Export notes for publishing
      - name: Export notes
        run: |
          yarn dendron publish export --target github --yes || \
          (echo "Export failed. Debug logs:" && cat dendron.log && exit 1)

      # Step 12: Deploy site using GitHub Pages
      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: pages
          publish_dir: docs/
          force_orphan: true
          # cname: example.com (Uncomment if using a custom domain)
