name: Build Dendron Static Site

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Setup Node.js to match local version
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.15.1'

      # Step 2: Checkout source code
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Step 3: Clear caches and Node modules
      - name: Clear caches
        run: rm -rf node_modules .next

      # Step 4: Install dependencies
      - name: Install dependencies
        run: yarn install

      # Step 5: Update critical dependencies
      - name: Update critical dependencies
        run: |
          yarn add react@latest react-dom@latest antd@latest
          yarn add --dev typescript@latest @types/react @types/react-dom @types/antd

      # Step 6: Remove private and template vaults
      - name: Remove private and template vaults
        run: |
          sed -i '/- fsPath: templates/,+3d' dendron.yml
          sed -i '/- fsPath: vault2/,+6d' dendron.yml

      # Step 7: Initialize or pull Next.js template
      - name: Initialize or pull Next.js template
        run: |
          (test -d .next) && \
          (echo 'Updating Dendron Next.js template...' && cd .next && git reset --hard && git pull && yarn && cd ..) || \
          (echo 'Initializing Dendron Next.js template...' && yarn dendron publish init)

      # Step 8: Restore Next.js cache
      - name: Restore Next.js cache
        uses: actions/cache@v2
        with:
          path: |
            .next/.next/cache
            .next/server/bundle
            .next/static/chunks
          key: ${{ runner.os }}-nextjs-${{ hashFiles('.next/yarn.lock', '.next/package-lock.json') }}-${{ hashFiles('.next/**.[jt]s', '.next/**.[jt]sx') }}

      # Step 9: Check Dendron version
      - name: Check Dendron version
        run: yarn dendron --version

      # Step 10: Build the project
      - name: Build the project
        run: |
          yarn build || (echo "Build failed. Debugging logs:" && ls -R . && exit 1)

      # Step 11: Export notes for publishing
      - name: Export notes
        run: |
          yarn dendron publish export --target github --yes || \
          (echo "Export failed. Debug logs:" && cat dendron.log && exit 1)

      # Step 12: Deploy site using GitHub Pages
      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: pages
          publish_dir: docs/
          force_orphan: true
